# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJBnMoGO3-vxnRjviEY42SpGtKCiiGD4
"""

import streamlit as st
import pandas as pd
from tsp_solver import solve_tsp

st.title("Travelling Salesman Problem – Delhi & 6 Cities")
st.write("""
This app uses **OR-Tools RoutingModel** to solve the TSP.
The model respects:
1. Each city is departed from exactly once
2. Each city is arrived at exactly once
3. x(i,j) are binary decision variables
Subtour elimination is handled internally by OR-Tools.
""")

# Distance matrix from your table (0 = Delhi)
distance_matrix = [
    [0,   233, 281, 260, 500, 250, 450],  # Delhi
    [233,   0, 240, 400, 335, 350, 260],  # Agra
    [281, 240,   0, 520, 590, 520, 570],  # Jaipur
    [260, 400, 520,   0, 650, 150, 700],  # Chandigarh
    [500, 335, 590, 650,   0, 530,  90],  # Lucknow
    [250, 350, 520, 150, 530,   0, 600],  # Dehradun
    [450, 260, 570, 700,  90, 600,   0],  # Kanpur
]

cities = ["Delhi", "Agra", "Jaipur", "Chandigarh", "Lucknow", "Dehradun", "Kanpur"]

st.subheader("Distance Matrix (km)")
df = pd.DataFrame(distance_matrix, index=cities, columns=cities)
st.dataframe(df)

if st.button("Solve TSP (Start from Delhi)"):
    route, total_dist = solve_tsp(distance_matrix, start_node=0)

    if route is None:
        st.error("No feasible route found by OR-Tools.")
    else:
        route_city_names = [cities[i] for i in route]

        st.success("Optimal (or near-optimal) route found:")
        st.write(" → ".join(route_city_names))
        st.write(f"Total distance: **{total_dist} km**")

        # Show route as a table with step numbers
        st.subheader("Route details")
        st.table(
            pd.DataFrame({
                "Step": list(range(len(route_city_names))),
                "City": route_city_names
            })
        )