# -*- coding: utf-8 -*-
"""tsp_solver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJBnMoGO3-vxnRjviEY42SpGtKCiiGD4
"""

from ortools.constraint_solver import pywrapcp, routing_enums_pb2

def solve_tsp(distance_matrix, start_node=0):
    """
    Solves the TSP using OR-Tools RoutingModel.

    distance_matrix[i][j] = d_ij
    start_node = index of starting city (Delhi = 0)

    Returns:
        route: list of node indices in visiting order including return to start
        total_distance: total cost of the tour
    """

    n = len(distance_matrix)

    # --- Create index manager ---
    # 1 vehicle, depot = start_node
    manager = pywrapcp.RoutingIndexManager(n, 1, start_node)

    # --- Create Routing Model ---
    routing = pywrapcp.RoutingModel(manager)

    # --- Distance callback ---
    def distance_callback(from_index, to_index):
        # Convert internal indices to node numbers
        from_node = manager.IndexToNode(from_index)
        to_node = manager.IndexToNode(to_index)
        return distance_matrix[from_node][to_node]

    transit_callback_index = routing.RegisterTransitCallback(distance_callback)

    # Objective: minimize total distance
    # This enforces: Minimize Σ Σ d_ij * x_ij
    routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

    # Search strategy (how OR-Tools explores solutions)
    search_params = pywrapcp.DefaultRoutingSearchParameters()
    search_params.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
    )
    # You could also add metaheuristics (local search) if needed

    # --- Solve ---
    solution = routing.SolveWithParameters(search_params)

    if not solution:
        return None, None

    # --- Extract route ---
    route = []
    index = routing.Start(0)  # vehicle 0
    total_distance = 0

    while not routing.IsEnd(index):
        node = manager.IndexToNode(index)
        route.append(node)
        next_index = solution.Value(routing.NextVar(index))
        total_distance += routing.GetArcCostForVehicle(index, next_index, 0)
        index = next_index

    # Add depot at the end to complete cycle
    route.append(manager.IndexToNode(routing.Start(0)))

    return route, total_distance